VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "bento/ubuntu-16.04"

  config.vm.define "dev_playground" do |playground|
  end

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 1
  end

  config.vm.network :private_network,
    ip: "10.0.100.2",
    netmask: "255.255.255.0"

  config.vm.network :forwarded_port, guest: 22, host: 22100, id: 'ssh'

  config.vm.provision "shell", path: "provision.sh"

  config.notify_forwarder.run_as_root = false
  config.notify_forwarder.port = 22111

end

# Ruby
# 2GB RAM, 1 rdzeń
# guest: 22, host: 22<3 oktet IP>
# notify_forwarder.port: host++
